services:
  - type: web
    name: prasad-voice-agent
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python3 -c "from langchain_huggingface import HuggingFaceEmbeddings; HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2', cache_folder='./.cache')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
